# Generated by Django 5.0 on 2024-01-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Electric')], verbose_name='category'),
        ),
    ]
